#include<stdio.h>
int main(){
int a[10][10];
int i,j,k;
//array generated by loop
for(i=0;i<10;i++){
    for(j=0,k=1;j<=10,k<=10;j++,k++){
            a[i][j]=k;
            printf("a[%d][%d]=[%d]\n",i,j,k);

    }

}
printf("-------------\n");

//print array , which is  generated by loop

for(i=0;i<10;i++){
    for(j=0;j<10;j++){
        printf("a[%d][%d]=[%d]\n",i,j,a[i][j]);
    }
}
    printf("-------------\n");

k=1;
while(k<=10){
   for(i=0;i<10;i++){

    for(j=0;j<10;j++){
        printf("%d ",a[i][j]*k);
}
    printf("\n");
    k++;

 }

}

}
